"""
FENIX Agent - Turkish Wellness Content Writer for CyraSoul.

This agent generates engaging Turkish wellness content using RAG-retrieved
knowledge and maintaining the CyraSoul brand voice.
"""

import os
from typing import Dict, Any, Optional, List
from dataclasses import dataclass, field
from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv()


@dataclass
class ContentRequest:
    """Request for content generation."""
    topic: str
    content_type: str = "blog"  # blog, product, social
    target_words: int = 2000
    keywords: List[str] = field(default_factory=list)
    product_focus: Optional[str] = None
    additional_context: Optional[str] = None


@dataclass
class ContentDraft:
    """Draft content generated by Fenix."""
    title: str
    content: str
    meta_description: str
    keywords_used: List[str]
    word_count: int
    sections: List[str]
    product_mentions: List[str]
    needs_review: bool = True


class FenixAgent:
    """
    FENIX - Turkish Wellness Content Writer.

    Generates engaging Turkish wellness content for CyraSoul using
    RAG-retrieved knowledge and brand guidelines.
    """

    SYSTEM_PROMPT = """Sen CyraSoul için Türkçe wellness içerik yazarısın. Adın FENIX.

## Görevin
- Bilgi tabanından wellness bilgilerini kullanarak içerik oluştur
- CyraSoul'un bilimsel ama samimi marka sesini koru
- Ürünleri doğal şekilde entegre et
- SEO-uyumlu başlık hiyerarşisi kullan
- Okuyucuya değer katan, eğitici içerikler yaz

## CyraSoul Ürünleri
- DailyGlow: Cilt parlaklığı ve enerji desteği
- DreamGlow: Gece onarımı ve kolajen desteği
- MindFuel: Zihinsel odaklanma ve kognitif destek
- Reset Button: Bitkisel detoks ve karaciğer desteği
- TheChill: Stres azaltma ve rahatlama

## Marka Sesi
- Bilimsel ama samimi ton
- Okuyucuya "sen" diye hitap et
- Teknik terimleri açıkla
- Pozitif ve motive edici ol
- Yargılayıcı olmaktan kaçın

## İçerik Yapısı
1. Dikkat çekici başlık (H1)
2. Giriş paragrafı (100-150 kelime)
3. Ana bölümler (H2 başlıklarla)
4. Alt bölümler (H3 başlıklarla gerekirse)
5. Sonuç ve eylem çağrısı

## Kurallar
- Makale başına maksimum 2-3 ürün referansı
- Doğrulanmamış sağlık iddiaları yapma
- Abartılı ifadelerden kaçın
- Her bölümde değerli bilgi sun

Çıktını aşağıdaki JSON formatında ver:
```json
{
  "title": "Makale Başlığı",
  "meta_description": "150-160 karakter meta açıklama",
  "content": "Tam makale içeriği (markdown formatında)",
  "keywords_used": ["anahtar", "kelimeler"],
  "product_mentions": ["DailyGlow", "MindFuel"]
}
```"""

    def __init__(
        self,
        model: str = "claude-sonnet-4-20250514",
        max_tokens: int = 4096
    ):
        """
        Initialize FENIX agent.

        Args:
            model: Claude model to use.
            max_tokens: Maximum tokens in response.
        """
        api_key = os.getenv("ANTHROPIC_API_KEY")
        if not api_key:
            raise ValueError("ANTHROPIC_API_KEY environment variable is required")

        self.client = Anthropic(api_key=api_key)
        self.model = model
        self.max_tokens = max_tokens

    def generate_content(
        self,
        request: ContentRequest,
        rag_context: Optional[str] = None,
        guardrails: Optional[str] = None
    ) -> ContentDraft:
        """
        Generate content for a given request.

        Args:
            request: Content generation request.
            rag_context: Retrieved context from knowledge base.
            guardrails: Content guardrails to follow.

        Returns:
            ContentDraft with generated content.
        """
        # Build the user message
        user_message = self._build_user_message(request, rag_context, guardrails)

        # Call Claude
        response = self.client.messages.create(
            model=self.model,
            max_tokens=self.max_tokens,
            system=self.SYSTEM_PROMPT,
            messages=[
                {"role": "user", "content": user_message}
            ]
        )

        # Parse response
        response_text = response.content[0].text
        return self._parse_response(response_text, request)

    def _build_user_message(
        self,
        request: ContentRequest,
        rag_context: Optional[str],
        guardrails: Optional[str]
    ) -> str:
        """Build the user message for content generation."""
        parts = []

        # Add topic and type
        parts.append(f"## İçerik Talebi")
        parts.append(f"**Konu:** {request.topic}")
        parts.append(f"**İçerik Türü:** {request.content_type}")
        parts.append(f"**Hedef Kelime Sayısı:** {request.target_words}")

        # Add keywords if provided
        if request.keywords:
            parts.append(f"**Anahtar Kelimeler:** {', '.join(request.keywords)}")

        # Add product focus if provided
        if request.product_focus:
            parts.append(f"**Odak Ürün:** {request.product_focus}")

        # Add RAG context
        if rag_context:
            parts.append("\n## Bilgi Tabanından Alınan İçerik")
            parts.append(rag_context)

        # Add guardrails
        if guardrails:
            parts.append("\n## İçerik Kuralları")
            parts.append(guardrails)

        # Add additional context
        if request.additional_context:
            parts.append("\n## Ek Bilgiler")
            parts.append(request.additional_context)

        # Add instruction
        parts.append("\n## Görev")
        parts.append("Yukarıdaki bilgileri kullanarak, CyraSoul marka sesine uygun, "
                    "SEO-optimize edilmiş Türkçe bir makale yaz. "
                    "Çıktını belirtilen JSON formatında ver.")

        return "\n".join(parts)

    def _parse_response(
        self,
        response_text: str,
        request: ContentRequest
    ) -> ContentDraft:
        """Parse Claude's response into ContentDraft."""
        import json
        import re

        # Try to extract JSON from response
        json_match = re.search(r'```json\s*(.*?)\s*```', response_text, re.DOTALL)

        if json_match:
            try:
                data = json.loads(json_match.group(1))
                content = data.get("content", response_text)
                title = data.get("title", request.topic)
                meta_description = data.get("meta_description", "")
                keywords_used = data.get("keywords_used", [])
                product_mentions = data.get("product_mentions", [])
            except json.JSONDecodeError:
                # Fallback to raw response
                content = response_text
                title = request.topic
                meta_description = ""
                keywords_used = request.keywords
                product_mentions = []
        else:
            # No JSON found, use raw response
            content = response_text
            title = request.topic
            meta_description = ""
            keywords_used = request.keywords
            product_mentions = []

        # Count words
        word_count = len(content.split())

        # Extract sections (H2 headers)
        sections = re.findall(r'^## (.+)$', content, re.MULTILINE)

        return ContentDraft(
            title=title,
            content=content,
            meta_description=meta_description,
            keywords_used=keywords_used,
            word_count=word_count,
            sections=sections,
            product_mentions=product_mentions,
            needs_review=True
        )

    def refine_content(
        self,
        draft: ContentDraft,
        feedback: str
    ) -> ContentDraft:
        """
        Refine content based on feedback.

        Args:
            draft: Current content draft.
            feedback: Feedback for improvement.

        Returns:
            Refined ContentDraft.
        """
        user_message = f"""## Mevcut İçerik
{draft.content}

## Geri Bildirim
{feedback}

## Görev
Geri bildirimi dikkate alarak içeriği iyileştir.
Çıktını belirtilen JSON formatında ver."""

        response = self.client.messages.create(
            model=self.model,
            max_tokens=self.max_tokens,
            system=self.SYSTEM_PROMPT,
            messages=[
                {"role": "user", "content": user_message}
            ]
        )

        response_text = response.content[0].text
        request = ContentRequest(topic=draft.title)
        return self._parse_response(response_text, request)
